var customerTypeTable = 'customer_type';
var stateTable = 'state';
var cityTable = 'city';
var userTable = 'user_master';
var customerTable = 'customer';
var customerUserTable = 'customer_user';
var userRoleTable = 'user_role';
var jwt = require('jsonwebtoken');
var config_master = require('../../../config_master');
var date = require('date-and-time');
var async = require('async');
var QueryBuilder = require('datatable');

exports.cusTypelistQuery = function(req,res) {
    var sql = "SELECT id,cust_type_name FROM "+customerTypeTable+" " +
    "where status = 'active'";
    return sql;
};

exports.statelistQuery = function(req,res) {
    var sql = "SELECT id,name FROM "+stateTable+" " +
    "WHERE `country_id` = 13";
    return sql;
};

exports.citylistQuery = function(req,res) {
    var sql = "SELECT id,name FROM "+cityTable+" " +
    "WHERE `state_id` = '"+req.body.stateId+"'";
    return sql;
};

exports.checkEmail = function(req,res) {
    var sql = "SELECT * FROM "+userTable+" WHERE ea_decode(email) = '" + req.body.email + "'";
    return sql;
};

exports.checkCustomerUniqueId = function(req,res) {
    if(req.body.id == 0){
        var sql = "SELECT customer_unique_id FROM "+customerTable+" WHERE customer_unique_id = '" + req.body.customer_unique_id + "'";
    } else {
        var sql = "SELECT customer_unique_id FROM "+customerTable+" WHERE customer_unique_id = '" + req.body.customer_unique_id + "' AND id != '"+req.body.id+"'";
    }
    return sql;
};

exports.customerlistQuery = function(req, res){

    var tableDefinition = {
        sDatabaseOrSchema: '`'+config_master.database.db+'`',
        sSelectSql: "CM.*, CT.cust_type_name,ST.name as sname,C.name as cname",
        sFromSql: " "+customerTable+" CM "+ 
        " LEFT JOIN "+customerTypeTable+" CT ON CT.id = CM.customer_type" +
        " LEFT JOIN "+stateTable+" ST ON ST.id=CM.state_id" +
        " LEFT JOIN "+cityTable+" C ON C.id=CM.city_id ",    
        sWhereAndSql: " CM.is_deleted = '0' ",
        aSearchColumns: ["ST.name", "C.name", "CT.cust_type_name", "CM.customer_name", "CM.customer_unique_id"],
    
    };
    var queryBuilder = new QueryBuilder(tableDefinition);
    // console.log(req.body);

    
    var requestQuery = req.body;
    for (let i = 0; i < requestQuery.columns.length; i++) {
        const element = requestQuery.columns[i];
        if (requestQuery.columns[i].searchable) {
            requestQuery.columns[i].searchable = 'true';
        }
        if (requestQuery.columns[i].orderable) {
            requestQuery.columns[i].orderable = 'true';
        }        
    }

    // Build an object of SQL statements
    var queries = queryBuilder.buildQuery(req.body);

    // Connect to the database
    var myDbObject = req.app.get('connection_enview_master');

    // Execute the SQL statements generated by queryBuilder.buildQuery
    myDbObject.query(queries.changeDatabaseOrSchema, function (err) {
        if (err) { res.status(403).json({ err }); }
        else {
            if (!queries.recordsFiltered) {
                queries.recordsFiltered = queries.recordsTotal;
            }

            // res.status(403).json(queries);
            // return false;
            async.parallel(
                {
                    recordsFiltered: function (cb) {
                        myDbObject.query(queries.recordsFiltered, cb);
                    },
                    recordsTotal: function (cb) {
                        myDbObject.query(queries.recordsTotal, cb);
                    },
                    select: function (cb) {
                        myDbObject.query(queries.select, cb);
                    }
                },
                function (err, results) {
                    if (err) { res.status(403).json({ err }); }
                    else {
                        // res.status(403).json(queryBuilder.parseResponse(results));
                        var token = jwt.sign(queryBuilder.parseResponse(results), config_master.API_SECRET, {
                            expiresIn: 86400 // expires in 24 hours
                        });
                        res.status(200).send({ auth: true, token: token });
                    }
                }
            );
        }
    });
}

// exports.customerlistQuery = function(req,res) {
    
//     var sql = "SELECT CM.*, CT.cust_type_name,ST.name as sname,C.name as cname " +
//     " FROM "+customerTable+" CM "+
//     " LEFT JOIN "+customerTypeTable+" CT ON CT.id = CM.customer_type" +
//     " LEFT JOIN "+stateTable+" ST ON ST.id=CM.state_id" +
//     " LEFT JOIN "+cityTable+" C ON C.id=CM.city_id WHERE CM.is_deleted = '0' order by CM.id desc";
//     return sql;
// };

exports.customerdeleteQuery = function(req,res) {
    var sql = "update "+customerTable+" " +
    "SET is_deleted = '1' WHERE `id` = '"+req.body.id+"'";
    return sql;
};

exports.viewUserQuery = function(req,res) {
    var sql = "SELECT CM.*,CT.cust_type_name,ST.name as sname,C.name as cname,U.name,ea_decode(U.mobile) as mobile,ea_decode(U.email) as email,U.id as customer_user_id " +
    " FROM "+customerTable+" CM "+
    " LEFT JOIN "+customerTypeTable+" CT ON CT.id = CM.customer_type" +
    " LEFT JOIN "+stateTable+" ST ON ST.id=CM.state_id" +
    " LEFT JOIN "+cityTable+" C ON C.id=CM.city_id" +
    " LEFT JOIN "+customerUserTable+" CU ON CU.customer_id=CM.id" +
    " LEFT JOIN "+userRoleTable+" UR ON UR.user_id=CU.user_id" +
    " LEFT JOIN "+userTable+" U ON U.id=UR.user_id" +
    " WHERE UR.role_id = 4 AND CM.id = '"+req.body.id+"'";
    return sql;
};